setup of mobile version home page
tarikbouari/My-Portfolio-Website pull request #1
Opened 2022-06-29 21:15 UTC by tarikbouari

**In this project I :**

- set up the linters 
-  created a navigation bar for the home page
- added a presentation session  to the home page

2022-06-29 22:00 UTC, wuletawwonte requested changes
# Hi @tarikbouari  👋🏿👋🏿👋🏿  

Good job so far!
There are some issues that you still need to work on to go to the next project! You have only a few more steps and you are done! 💪 💪 💪 

![giphy](https://user-images.githubusercontent.com/74506933/153382064-ed760a8c-4f4a-48d6-b1f0-1aa9e5135097.gif)

## TO HIGHLIGHT: 
- Your project is professional ✔️ 
- Correct Github Flow ✔️
- Your PR has a proper title and description ✔️
- Nice commit history ✔️
- Well structured files ✔️ 

## Required Changes ♻️
_Please check the comments under the review as well._

- [ ] Please change the name of your HTML file to `index.html` because web servers usually open your project from index.html file and this file is the default file that gets opened on page load.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-29 22:00 UTC, wuletawwonte commented on README.md
> +- LinkedIn: [tarikbouari](https://linkedin.com/in/linkedinhandle)
- [ ] [OPTIONAL] Please change the link to the social media accounts. You did good using the template from Microverse but please try to update the content.

2022-06-29 22:00 UTC, wuletawwonte commented on .gitignore
> +images/
- [ ] Please remove images folder from the `.gitignore` file. All the contents of the images folder should be available in the git repository.

2022-06-29 22:00 UTC, wuletawwonte commented on portfolio.html
> +        </div>
- [ ] Please remove the status-bar block of code from your project. It is just part of the mockup in the Figma design. It is not supposed to be implemented.

2022-06-29 22:00 UTC, wuletawwonte commented on portfolio.html
> +    <header class="header">
- [ ] Please only wrap the Toolbar with the `header` tag. Kindly move the section with the class name `presentaion` out of the header HTML element.

2022-06-29 22:00 UTC, wuletawwonte commented on portfolio.html
> +                    <span class="logo blue">My logo</span>
- [ ] I think this should be an `anchor` tag instead of `span`. It is the logo of the website, so it needs to be clickable and navigate to the homepage of the website. So please change the tag from `span` to `a` tag.

2022-06-29 22:00 UTC, wuletawwonte commented on portfolio.html
> +                    <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" class="icon blue" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path fill="currentColor" d="M4 6h1
- [ ] [OPTIONAL] Please save the SVG file in the images folder and reference it as an image.

2022-06-29 22:00 UTC, wuletawwonte commented on portfolio.html
> +            </div>
- [ ] Kindly use `ul` tag to group the whole list of icons and use `li` tag for each one.

2022-06-29 22:00 UTC, wuletawwonte commented on style.css
> +@media screen and (max-width: 768px) {
- [ ] Since the website is mobile-first you can remove the media query now. Because the default CSS is for the mobile viewport width and I think you start writing media queries for the desktop version.

2022-06-30 09:41 UTC, tarikbouari commented on README.md
> +- LinkedIn: [tarikbouari](https://linkedin.com/in/linkedinhandle)
I tried to fix it, but since it can't change the color of the SVG image;  I stick to my code.

2022-06-30 09:51 UTC, sumairq approved these changes
### Hi @tarikbouari , 

<img src="https://media2.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 10:54 UTC, merged