Built different sections
tarikbouari/My-Portfolio-Website pull request #2
Opened 2022-06-30 18:20 UTC by tarikbouari

In this project I:

- created a project section with a grid and flex-box on the home page
- created about section and list items 
- fixed linters and updated my code.

2022-06-30 22:11 UTC, cwaku requested changes
Hi @tarikbouari 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
There are a few issues 🐛  that you still need to work 🛠️  on to go to the next project ⏭️  but you are almost there! 🏃🏾 

## Highlights
- [ ] Good commit history 👍🏾 
- [ ] Meaningful PR title and description 💯 
- [ ] Correct use of GitHub flow 🥇 
- [ ] Linters passed 👍🏾 
- [ ] Professional repo 💯 

## Required Changes ♻️
It's OK to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips 🌟  that can improve your code quality 💯 and help you get a better job 💼.

I will guide 📔 you through fixing 🛠️ these bugs, follow my comments down below and make sure you don't miss any of them, in order to get your project approved ✅

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 22:11 UTC, cwaku commented on index.html
> +            <p class="blue text">LET’S CONNECT</p>
- [ ] It is required that you use a header tag `hx` for the "Let's connect" subtitle. Kindly fix that.

2022-06-30 22:11 UTC, cwaku commented on index.html
> +                            </div>
- [ ] The technology in each category(e.g., "JavasScript", "HTML" and "CSS") are also a list `ul` and each of them a `li`. I suggest you fix that

2022-06-30 22:11 UTC, cwaku commented on index.html
> +                        <img src="images/angle-right.svg" class="arrow icon" alt="arrow-down">
- [ ] It happens that your arrows here are not displaying as it shows on the figma design. I looked into it and found that there's a padding bottom being applied to them with CSS. Kindly fix that. 

##### Figma Design
![image](https://user-images.githubusercontent.com/29071984/176786923-32bdf097-2e47-4a53-a2e5-b9e8aeb007fe.png)

##### Your Design
![image](https://user-images.githubusercontent.com/29071984/176786512-46736a7e-26f9-4be5-afbf-aac30827c022.png)

2022-07-01 09:26 UTC, codecaiine approved these changes
Hi @tarikbouari , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

 Good commit history :heavy_check_mark: 
 Good Pull Request title and description :heavy_check_mark: 
 Good use of github workflow :heavy_check_mark: 
 No Linters errors :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-01 09:37 UTC, merged